### PR TITLE
Fastapi

### PR DESCRIPTION
**Pull request by BeckySharp**
fastapi server for the speech analysis.  It works for me here, can someone please verify it works chez eux?
thanks!
I added three of you for good measure :)

### CODE REVIEW

**Review by adarshp — CHANGES_REQUESTED** [review]
Thanks @BeckySharp  - I haven't tested it myself yet (I'll leave that up to @vincentraymond-ua ), but in general it looks good to me. 

I would like to request a minor change though - could you please remove the `mmc_server/environment.yml` file?

**Comment by BeckySharp** [comment]
I can -- is it not useful for people who use conda?

**Comment by adarshp** [comment]
@


> I can -- is it not useful for people who use conda?
> […](#)

Not sure - although I have used Anaconda in the past, I favor just using pip and virtual environments now. Will others be able to use it out of the box? I see that there is a machine-specific line in the file:

```
prefix: /Users/bsharp/anaconda/envs/mmc
```

**Comment by BeckySharp** [comment]
good catch, and i don't have big feelings about it
i'll remove it, sorry for the delay

**Comment by BeckySharp** [comment]
@adarshp done in latest commit, thanks!

**Comment by adarshp** [comment]
> @adarshp done in latest commit, thanks!

Thanks @BeckySharp !

**Review by adarshp — APPROVED** [review]

**Pull request merged**
